function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Oct-2019 09:51:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','$IoU (DAAE)$','LineStyle','--');
set(plot1(2),'DisplayName','$IoU (DAE)$','LineStyle','--');
set(plot1(3),'DisplayName','$F_1-measure (DAAE)$');
set(plot1(4),'DisplayName','$F_1-measure (DAE)$');

% Create ylabel
ylabel('$ IoU / F_1-measure $','FontName','Times','Interpreter','latex');

% Create xlabel
xlabel('Sub-region','FontName','Times','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[1 27]);
box(axes1,'on');
grid(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.508067607479548 0.138174606892798 0.306483834522593 0.150238092059181],...
    'Interpreter','latex');

