function W_plot(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-Oct-2019 12:15:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',2);

% Create ylabel
ylabel('$F_1-meansure$','FontSize',14,'FontName','Times',...
    'Interpreter','latex');

% Create xlabel
xlabel('$W_h$','FontSize',14,'FontName','Times','Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.1 0.9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1.2]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'GridLineStyle','--');
