function [fitresult, gof] = createNormal_H(x, y) %通过对散点数据直接进行拟合，通过x，y数据点直接进行拟合， 得到一个正态分布曲线
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'normal_H' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jul-2019 20:07:11


%% Fit: 'normal_H'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [5755 117.25 4.71675948369911];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'normal_H' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'normal_H', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


